disabled_rules:
  - trailing_comma
  - opening_brace
  - static_over_final_class
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - for_where
  - multiple_closures_with_trailing_closure

excluded:
 - build

line_length:
  warning: 100
  error: 120

identifier_name:
  min_length: 1
  max_length: 40

type_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false

type_body_length:
  warning: 500
  error: 800

function_body_length:
  warning: 80
  error: 100

function_parameter_count:
  warning: 8
  error: 10